source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.2.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.6"

# use mariadb
gem 'mysql2'

# Rails Locale Data Repository [https://github.com/svenfuchs/rails-i18n]
gem 'rails-i18n'

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
gem "bcrypt", "~> 3.1.7"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem "image_processing", "~> 1.2"

# Use Active Storage validations [https://github.com/igorkasyanchuk/active_storage_validations]
gem 'active_storage_validations'

# Rails CSRF Protection
gem 'omniauth-rails_csrf_protection'

# Standardized Multi-Provider Authentication
gem 'omniauth-twitter'
gem 'omniauth-github'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :test do
  # Use rspec about test framework
  gem 'rspec-rails', '~> 5.0.0'
  # Use test data creator
  gem 'factory_bot_rails'
  # using assert_template method in test
  gem 'rails-controller-testing'
end
